import type { Conversation, CodingRun, Issue, KnowledgeArticle } from "./types";

export const seedConversations: Conversation[] = [
  {
    id: "conv-cliente-exemplo",
    chatType: "direct",
    name: "Cliente Exemplo",
    company: "Workspace de demonstração",
    phone: "+55 11 90000-0000",
    initials: "CE",
    accent: "#7c91ff",
    status: "open",
    attention: "needs_attention",
    aiMode: "draft",
    automationState: "ai_active",
    unread: 3,
    lastMessage: "Fechamento continua travando",
    lastTime: "3m",
    lastMessageAt: "2026-08-03T14:08:00",
    issueId: "issue-24",
    issueLabel: "TEC-24",
    priority: "Urgent",
    assignee: "Marina",
    messages: [
      {
        id: "m-ce-1",
        conversationId: "conv-cliente-exemplo",
        direction: "inbound",
        sender: "Contato demo",
        text: "Oi, pessoal. O fechamento do caixa trava quando tento finalizar o último pedido.",
        time: "13:58",
        type: "text",
      },
      {
        id: "m-ce-2",
        conversationId: "conv-cliente-exemplo",
        direction: "inbound",
        sender: "Contato demo",
        text: "Já reiniciei o tablet e continua igual. Preciso fechar a loja em 20 minutos.",
        time: "14:02",
        type: "text",
      },
      {
        id: "m-ce-3",
        conversationId: "conv-cliente-exemplo",
        direction: "outbound",
        sender: "Marina",
        text: "Entendi. Vou investigar agora e te atualizo por aqui.",
        time: "14:04",
        type: "text",
        status: "read",
      },
      {
        id: "m-ce-4",
        conversationId: "conv-cliente-exemplo",
        direction: "inbound",
        sender: "Contato demo",
        text: "Fechamento continua travando",
        time: "14:08",
        type: "text",
      },
    ],
  },
  {
    id: "conv-dona-batata",
    chatType: "direct",
    name: "Dona Batata",
    company: "Dona Batata Delivery",
    phone: "+55 21 98812-4401",
    initials: "DB",
    accent: "#e9a75d",
    status: "open",
    attention: "waiting_customer",
    aiMode: "safe_auto",
    automationState: "ai_active",
    unread: 0,
    lastMessage: "O pagamento via Pix caiu, mas o pedido não atualizou.",
    lastTime: "18m",
    lastMessageAt: "2026-08-03T13:53:00",
    issueId: "issue-23",
    issueLabel: "TEC-23",
    priority: "High",
    assignee: "João",
    messages: [
      {
        id: "m-db-1",
        conversationId: "conv-dona-batata",
        direction: "inbound",
        sender: "Paula · Dona Batata",
        text: "O pagamento via Pix caiu, mas o pedido não atualizou.",
        time: "13:42",
        type: "text",
      },
      {
        id: "m-db-2",
        conversationId: "conv-dona-batata",
        direction: "outbound",
        sender: "João",
        text: "Recebi. Pode me enviar o número do pedido?",
        time: "13:45",
        type: "text",
        status: "read",
      },
      {
        id: "m-db-3",
        conversationId: "conv-dona-batata",
        direction: "inbound",
        sender: "Paula · Dona Batata",
        text: "#10482",
        time: "13:53",
        type: "text",
      },
    ],
  },
  {
    id: "conv-rodrigo",
    chatType: "direct",
    name: "Rodrigo Veículos",
    company: "Rodrigo Veículos",
    phone: "+55 31 99102-3318",
    initials: "RV",
    accent: "#8ecb9c",
    status: "open",
    attention: "ai_handling",
    aiMode: "draft",
    automationState: "ai_active",
    unread: 1,
    lastMessage: "Daria para exportar os leads por vendedor?",
    lastTime: "42m",
    lastMessageAt: "2026-08-03T13:29:00",
    issueId: "issue-22",
    issueLabel: "TEC-22",
    priority: "Medium",
    assignee: "AI",
    messages: [
      {
        id: "m-rv-1",
        conversationId: "conv-rodrigo",
        direction: "inbound",
        sender: "Rodrigo · Rodrigo Veículos",
        text: "Daria para exportar os leads por vendedor? Hoje só consigo ver o total.",
        time: "13:29",
        type: "text",
      },
      {
        id: "m-rv-2",
        conversationId: "conv-rodrigo",
        direction: "outbound",
        sender: "AI draft",
        text: "Vou verificar as opções de exportação disponíveis e já te retorno.",
        time: "13:30",
        type: "text",
        aiGenerated: true,
        status: "delivered",
      },
    ],
  },
  {
    id: "conv-lucia",
    chatType: "direct",
    name: "Lucia Carvalho",
    company: "Clínica Horizonte",
    phone: "+55 11 98110-0290",
    initials: "LC",
    accent: "#b997e8",
    status: "resolved",
    attention: "none",
    aiMode: "draft",
    automationState: "ai_active",
    unread: 0,
    lastMessage: "Obrigada, agora funcionou!",
    lastTime: "2h",
    lastMessageAt: "2026-08-03T12:11:00",
    issueId: "issue-19",
    issueLabel: "TEC-19",
    priority: "Low",
    assignee: "Marina",
    messages: [
      {
        id: "m-lc-1",
        conversationId: "conv-lucia",
        direction: "inbound",
        sender: "Lucia · Clínica Horizonte",
        text: "A senha não estava sendo aceita no computador novo.",
        time: "11:58",
        type: "text",
      },
      {
        id: "m-lc-2",
        conversationId: "conv-lucia",
        direction: "outbound",
        sender: "Marina",
        text: "Ajustei o acesso e enviei um novo convite. Pode tentar novamente?",
        time: "12:05",
        type: "text",
        status: "read",
      },
      {
        id: "m-lc-3",
        conversationId: "conv-lucia",
        direction: "inbound",
        sender: "Lucia · Clínica Horizonte",
        text: "Obrigada, agora funcionou!",
        time: "12:11",
        type: "text",
      },
    ],
  },
  {
    id: "conv-otto",
    chatType: "direct",
    name: "Otto Martins",
    company: "Otto Studio",
    phone: "+55 48 99603-7754",
    initials: "OM",
    accent: "#6fb6c8",
    status: "open",
    attention: "needs_attention",
    aiMode: "off",
    automationState: "ai_active",
    unread: 1,
    lastMessage: "Conseguem revisar o acesso da equipe?",
    lastTime: "3h",
    lastMessageAt: "2026-08-03T11:12:00",
    assignee: "Unassigned",
    messages: [
      {
        id: "m-om-1",
        conversationId: "conv-otto",
        direction: "inbound",
        sender: "Otto · Otto Studio",
        text: "Conseguem revisar o acesso da equipe?",
        time: "11:12",
        type: "text",
      },
    ],
  },
];

export const seedIssues: Issue[] = [
  {
    id: "issue-24",
    identifier: "TEC-24",
    title: "Fechamento de caixa trava no último pedido",
    type: "Production Bug",
    priority: "Urgent",
    status: "In Progress",
    assignee: "Marina",
    labels: ["checkout", "production"],
    customer: "Cliente Exemplo",
    conversationId: "conv-cliente-exemplo",
    source: "Conversation",
    summary:
      "O fechamento do caixa não conclui quando a loja tenta finalizar o último pedido do turno.",
    impact:
      "A operação não consegue encerrar o caixa e há risco de atraso no fechamento da loja.",
    updatedAt: "3m ago",
    createdAt: "Today, 13:58",
    codexRuns: 1,
  },
  {
    id: "issue-23",
    identifier: "TEC-23",
    title: "Pagamento Pix não atualiza pedido",
    type: "Billing",
    priority: "High",
    status: "Triage",
    assignee: "João",
    labels: ["payments", "pix"],
    customer: "Dona Batata",
    conversationId: "conv-dona-batata",
    source: "Conversation",
    summary: "Webhook de pagamento recebido sem refletir o status do pedido.",
    impact: "Pedidos pagos ficam retidos no fluxo até uma intervenção manual.",
    updatedAt: "18m ago",
    createdAt: "Today, 13:42",
    codexRuns: 0,
  },
  {
    id: "issue-22",
    identifier: "TEC-22",
    title: "Exportar leads por vendedor",
    type: "Feature",
    priority: "Medium",
    status: "Backlog",
    assignee: "AI",
    labels: ["leads", "reporting"],
    customer: "Rodrigo Veículos",
    conversationId: "conv-rodrigo",
    source: "Conversation",
    summary: "Adicionar agrupamento por vendedor na exportação de leads.",
    impact:
      "O time comercial precisa cruzar dados manualmente para acompanhar a performance.",
    updatedAt: "42m ago",
    createdAt: "Today, 13:29",
    codexRuns: 0,
  },
  {
    id: "issue-21",
    identifier: "TEC-21",
    title: "Revisar permissões do workspace",
    type: "Task",
    priority: "Low",
    status: "Todo",
    assignee: "Marina",
    labels: ["security", "internal"],
    source: "Internal",
    summary: "Auditar permissões de agentes e viewers nas rotas operacionais.",
    impact: "Reduzir risco de exposição entre workspaces.",
    updatedAt: "Yesterday",
    createdAt: "Aug 02, 09:20",
    codexRuns: 0,
  },
  {
    id: "issue-19",
    identifier: "TEC-19",
    title: "Convite de acesso não aceita senha nova",
    type: "Bug",
    priority: "Low",
    status: "Done",
    assignee: "Marina",
    labels: ["auth"],
    customer: "Lucia Carvalho",
    conversationId: "conv-lucia",
    source: "Conversation",
    summary:
      "Convite para uma nova pessoa falhava em um dispositivo recém-configurado.",
    impact: "Usuários não conseguiam completar o primeiro acesso.",
    updatedAt: "2h ago",
    createdAt: "Aug 02, 11:45",
    codexRuns: 1,
  },
  {
    id: "issue-18",
    identifier: "TEC-18",
    title: "Atualizar texto da tela de checkout",
    type: "Task",
    priority: "No priority",
    status: "Review",
    assignee: "João",
    labels: ["copy", "checkout"],
    source: "Internal",
    summary: "Ajustar texto do estado de processamento.",
    impact: "Melhorar entendimento do cliente durante a confirmação.",
    updatedAt: "Aug 01",
    createdAt: "Aug 01, 15:42",
    codexRuns: 0,
  },
];

export const seedRuns: CodingRun[] = [
  {
    id: "run-204",
    issueId: "issue-24",
    issueIdentifier: "TEC-24",
    mode: "Propose fix",
    status: "Running",
    progress: 68,
    startedAt: "14:11",
    duration: "02:48",
    summary:
      "Investigando o fechamento e comparando o fluxo de finalização com os estados de pagamento pendente.",
    caseId: "case-204",
    caseStatus: "active",
    stage: "investigation",
    provider: "gemini",
    suspicionScore: 0.78,
    verdict: "pending",
    decision: "pending",
    evidence: [
      {
        kind: "conversation",
        label: "Relato recorrente do cliente",
        detail: "O fechamento trava depois de um pagamento pendente.",
      },
      {
        kind: "release",
        label: "Versão afetada identificada",
        detail: "A regressão começa na versão atual.",
      },
    ],
    files: ["src/checkout/close-register.ts", "src/orders/order-state.ts"],
    events: [
      {
        id: "e-1",
        label: "repository_prepared",
        detail: "Branch isolada criada a partir de main",
        time: "14:11:08",
        tone: "neutral",
      },
      {
        id: "e-2",
        label: "search_performed",
        detail: "Localizados 4 arquivos relevantes",
        time: "14:11:32",
        tone: "accent",
      },
      {
        id: "e-3",
        label: "analysis_started",
        detail: "Comparando estados do último pedido",
        time: "14:12:10",
        tone: "accent",
      },
      {
        id: "e-4",
        label: "file_read",
        detail: "Fluxo de fechamento carregado",
        time: "14:12:51",
        tone: "neutral",
      },
    ],
  },
  {
    id: "run-201",
    issueId: "issue-19",
    issueIdentifier: "TEC-19",
    mode: "Implement fix",
    status: "Completed",
    progress: 100,
    startedAt: "Yesterday, 16:04",
    duration: "08:21",
    summary:
      "Corrigido o parsing do convite quando o dispositivo ainda não possui uma sessão local.",
    caseId: "case-201",
    caseStatus: "awaiting_human",
    stage: "pull_request",
    provider: "claude",
    suspicionScore: 0.93,
    verdict: "confirmed",
    decision: "autofix",
    evidence: [
      {
        kind: "reproduction",
        label: "Falha reproduzida em workspace isolado",
      },
      {
        kind: "trace",
        label: "Token legado chega sem sessão local",
      },
    ],
    pullRequest: {
      number: 42,
      url: "https://github.com/kdo-vini/mend/pull/42",
      head: "ops/TEC-19-fix-invite",
      base: "main",
      draft: true,
    },
    healthStatus: "pending",
    customerResponseStatus: "drafted",
    branch: "ops/TEC-19-fix-invite",
    commit: "7d31c4a",
    files: ["src/auth/invite.ts", "src/auth/invite.test.ts"],
    diff: "diff --git a/src/auth/invite.ts b/src/auth/invite.ts\n--- a/src/auth/invite.ts\n+++ b/src/auth/invite.ts\n@@ -1 +1 @@\n-parseLegacyInvite(token)\n+parseInviteToken(token)",
    checks: [{ name: "test", exitCode: 0, output: "12 tests passed" }],
    events: [
      {
        id: "e-5",
        label: "commit_created",
        detail: "Commit local 7d31c4a criado",
        time: "16:12:25",
        tone: "success",
      },
      {
        id: "e-6",
        label: "tests_completed",
        detail: "12 testes aprovados",
        time: "16:12:02",
        tone: "success",
      },
      {
        id: "e-7",
        label: "diff_ready",
        detail: "Patch pronto para revisão",
        time: "16:11:48",
        tone: "accent",
      },
    ],
  },
  {
    id: "run-198",
    issueId: "issue-18",
    issueIdentifier: "TEC-18",
    mode: "Investigate",
    status: "Failed",
    progress: 44,
    startedAt: "Aug 01, 15:52",
    duration: "01:07",
    summary: "O runner não conseguiu acessar a pasta de trabalho configurada.",
    files: [],
    events: [
      {
        id: "e-8",
        label: "run_failed",
        detail: "Workspace path não encontrado",
        time: "15:53:07",
        tone: "danger",
      },
    ],
  },
];

export const seedKnowledge: KnowledgeArticle[] = [
  {
    id: "kb-1",
    title: "Como lidar com pagamentos Pix pendentes",
    category: "Payments",
    updatedAt: "Hoje, 10:42",
    excerpt:
      "Checklist de confirmação do webhook, pedido e reconciliação manual.",
    status: "Published",
  },
  {
    id: "kb-2",
    title: "Fechamento de caixa: diagnóstico rápido",
    category: "Checkout",
    updatedAt: "Ontem, 16:20",
    excerpt: "Sinais comuns de travamento e evidências úteis para engenharia.",
    status: "Published",
  },
  {
    id: "kb-3",
    title: "Política de respostas automáticas",
    category: "Support",
    updatedAt: "Jul 29",
    excerpt:
      "Quando a IA pode responder com segurança e quando deve pedir ajuda humana.",
    status: "Draft",
  },
];
